nome = input ("Digite seu nome?")
print ("Prazer em te conhecer {:20}!".format(nome))
print ("Prazer em te conhecer {:>20}!".format(nome))
print ("Prazer em te conhecer {:<20}!".format(nome))
print ("="*40)
print ("Prazer em te conhecer {}".format(nome))
print ("="*40)