algo = input ("Digite algo:")
print ("O tipo primitivo desse valor e", type(algo))
print ("So tem espaços?`{}".format(algo.isspace()))
print ("É um numero?{}".format(algo.isnumeric()))
print ("É um alfabetico?{}".format(algo.isalpha()))
print ("É alfanumerico?{}".format(algo.isalnum()))
print ("É maiusculas?{}".format(algo.isupper()))
print ("É minusculas?{}".format(algo.islower()))
print ("É capitalizada?{}".format(algo.istitle()))
